### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simsurace** [kyungminlee/SuperLU.jl#3]
Hi, this code does not have a license. Would you be willing to release under the MIT license?

**Comment by ericphanson** [comment]
just to add that [since this package is registered, it really does need a license](https://github.com/JuliaRegistries/General?tab=readme-ov-file#registering-a-package-in-general):

> Registered packages MUST have an [Open Source Initiative approved license](https://opensource.org/licenses), clearly marked via the license file (see below for definition) in the package repository.

**Comment by kyungminlee** [comment]
MIT LICENSE file has been added: 4569f2ad, 67ee7e8d
